BelarusLib/Controllers/TestController.cs
using BelarusLib.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BelarusLib.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Test
        public ActionResult Index()
        {
            var quizzes = context.Quizzes.Where(p => p.QuizIsPrivate == false);
            return View(quizzes);
        }
        public ActionResult Start(int id)
        {
            var quiz = context.Quizzes.Find(id);
            long secinterval = (quiz.QuizDuration.Hours * 3600 * 1000) + (quiz.QuizDuration.Minutes * 60 * 1000) + (quiz.QuizDuration.Seconds * 1000);
            ViewBag.Interval = secinterval;
            return View(quiz);
        }
        [HttpPost]
        public async Task<ActionResult> Start(Quiz quiz, List<int> queid, List<string> choices)
        {
            int count = 0;
            var userid = User.Identity.GetUserId();
            for (int i = 0; i < queid.Count; i++)
            {
                var question = context.Questions.Find(queid[i]);
                if (!String.IsNullOrEmpty(choices[i]))
                    choices[i] = choices[i].ToLower();
                if (String.Equals(question.QuestionAnswer, choices[i]))
                    count++;
            }
            int mark = 10 * count / queid.Count;
            Result result = new Result
            {
                QuizId = quiz.QuizId,
                UserId = userid,
                ResultDate = DateTime.Now,
                ResultScore = mark,

            };
            context.Results.Add(result);
            await context.SaveChangesAsync();
            return RedirectToAction("ShowResult", new { id = result.ResultId, count });
        }
        public ActionResult ShowResult(int id, int count)
        {
            ViewBag.Count = count;
            var results = context.Results.Include(q => q.Quiz).ToList();
            Result result = results.Find(i => i.ResultId == id);
            return View(result);
        }
    }
}

BelarusLib/Views/Test/Index.cshtml
@model IEnumerable<BelarusLib.Models.Quiz>

@{
    ViewBag.Title = "Тэсты";
}

<section>
    <div class="container">
        <h1 class="text-center">Тэсты</h1>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">@item.QuizName</div>
                        <div class="card-body">
                            <p>Апісанне: @item.QuizDescription</p>
                            <p>Колькасць пытанняў: @item.Questions.Count()</p>
                            <p>Працягласць: @item.QuizDuration</p>
                        </div>
                        <div class="card-footer">
                            @Html.ActionLink("Пачаць", "Start", new { id = item.QuizId })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

BelarusLib/Views/Test/ShowResult.cshtml
@model BelarusLib.Models.Result
@using BelarusLib.Models

@{
    ViewBag.Title = "Вынік";
}

<section>
    <div class="container">
        <h2>Вынік</h2>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayName("Тэст")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Quiz.QuizName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ResultScore)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ResultScore)
                </dd>

                <dt>
                    @Html.DisplayName("Правільных пытанняў")
                </dt>

                <dd>
                    @ViewBag.Count
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ResultDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ResultDate)
                </dd>
            </dl>
        </div>
        <p>
            @Html.ActionLink("На галоўную", "Index", "Test", new { @class = "butn butn-primary navbar-butn butn-shadow butn-gradient" })
        </p>
    </div>
</section>

BelarusLib/Views/Test/Start.cshtml
@model BelarusLib.Models.Quiz
@using BelarusLib.Models

@{
    ViewBag.Title = Model.QuizName;
    ApplicationDbContext db = new ApplicationDbContext();
    var questions = db.Questions.Where(q => q.QuizId == Model.QuizId).ToList();
    Random random = new Random();
    int count = 0;
    int qcount = 1;
    for (int i = questions.Count - 1; i >= 1; i--)
    {
        int j = random.Next(i + 1);
        // обменять значения data[j] и data[i]
        var temp = questions[j];
        questions[j] = questions[i];
        questions[i] = temp;
    }
}

<section>
    <div class="container">
        <h2>@Model.QuizName</h2>

        <hr />
        <h4 class="text-center" id="time"></h4>
        <hr />
        @using (Html.BeginForm("Start", "Test", FormMethod.Post, new { id = "form" }))
        {
            @Html.HiddenFor(model => model.QuizId)
            foreach (var question in questions)
            {
                <input type="hidden" name="queid[@count]" value=@question.QuestionId>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">Пытанне @qcount</div>
                        <div class="card-body">
                            <h5 class="card-title">@question.QuestionText</h5>
                            @if (question.QuestionImage != null)
                            {
                                <p>@Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(question.QuestionImage) + "\" />")</p>
                            }
                            @if (question.Choices.Count != 0)
                            {
                                <p>
                                    @foreach (var choice in question.Choices)
                                    {
                                        <label class="radio-inline">
                                            <input type="radio" value="@choice.ChoiceText" name="choices[@count]"> @choice.ChoiceText
                                        </label><br />
                                    }
                                    <input type="hidden" value="null" name="choices[@count]">
                                </p>
                            }
                            else
                            {
                                <p>
                                    <input type="text" name="choices[@count]" class="form-control" />
                                </p>
                            }
                        </div>
                    </div>
                    <br />
                </div>
                count++;
                qcount++;
            }
            <input type="submit" value="Завяршыць" class="butn butn-primary navbar-butn butn-shadow butn-gradient" />
        }
    </div>
</section>

@section Scripts {
    <script>
        setInterval(submit_me, @ViewBag.Interval);
        function submit_me() {
            $('#form').submit();
        }

        function startTimer(duration, display) {
            var timer = duration, minutes, seconds;
            setInterval(function () {
                minutes = parseInt(timer / 60, 10)
                seconds = parseInt(timer % 60, 10);

                minutes = minutes < 10 ? "0" + minutes : minutes;
                seconds = seconds < 10 ? "0" + seconds : seconds;

                display.textContent = minutes + ":" + seconds;

                if (--timer < 0) {
                    timer = duration;
                }
            }, 1000);
        }

        window.onload = function () {
            var time = @ViewBag.Interval / 1000,
                display = document.querySelector('#time');
            startTimer(time, display);
        };

    </script>
}